import type { Metadata } from "next";
import "./globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";
import Footer from "@/components/footer";
import InfoBar from "@/components/infoBar";
import Navbar from "@/components/navbar";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Elige los pesos necesarios
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-page-bg ${plusJakartaSans.className} antialiased`}>
        <InfoBar />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
