import type { Metadata } from "next";
import "./globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";
import Footer from "@/components/footer";
import InfoBar from "@/components/infoBar";
import Navbar from "@/components/navbar";
import BottomNavigationBar from "@/components/bottomNavigationBar";
import { WishListProvider } from "@/context/AppContext";
import TansTackProvider from "@/components/provider/tansTackProvider";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-page-bg ${plusJakartaSans.className} antialiased`}>
        <WishListProvider>
          <InfoBar />
          <TansTackProvider>
            <Navbar />
            {children}
          </TansTackProvider>
          <Footer />
          <BottomNavigationBar />
        </WishListProvider>
      </body>
    </html>
  );
}
